# Thank you, https://ruan.dev/blog/2020/09/20/setup-a-nfs-server-with-docker
# https://www.ibm.com/docs/en/ibm-mq/9.2?topic=managers-create-multi-instance-queue-manager
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ${NFS_STORAGE_DIR}:/data
    ports:
      - 2049:2049
    networks:
      admin:
        ipv4_address: 10.0.11.10
      discovery:
        ipv4_address: 192.0.11.10
    healthcheck:
      test: [ "CMD-SHELL", "touch ready.log" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  mq-active-node:
    build:
      context: ./mq/
      args:
        LOG_FILES_DIR: ${LOG_FILES_DIR}
        DATA_FILES_DIR: ${DATA_FILES_DIR}
    image: rhel-mq
    depends_on:
      nfs:
        condition: service_healthy
        restart: true
    environment:
      - IS_ACTIVE_NODE=1
      - DATA_FILES_DIR_ENV=${DATA_FILES_DIR}
      - LOG_FILES_DIR_ENV=${LOG_FILES_DIR}
    volumes:
      - qmgr-data:${QUEUE_MANAGER_DIR}
    networks:
      admin:
        ipv4_address: 10.0.11.20
      discovery:
        ipv4_address: 192.0.11.20

#  mq-stand-by-node:
#    build:
#      context: ./mq/
#    image: rhel-mq
#    networks:
#      admin:
#        ipv4_address: 10.0.11.30
#      discovery:
#        ipv4_address: 192.0.11.30

volumes:
  qmgr-data:
    driver_opts:
      type: "nfs"
      o: "addr=192.0.11.10,vers=4,hard,intr,rw"
      device: ":/"

networks:
  admin:
    ipam:
      driver: default
      config:
        - subnet: "10.0.11.0/24"
  discovery:
    ipam:
      driver: default
      config:
        - subnet: "192.0.11.0/24"